
import java.awt.Button;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import javafx.util.Pair;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author night
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        initComponents2();
    }
    
    public static int count = 0;
    //number of student
    public static boolean[][] selectedButton = new boolean[6][8];
    //the button selected in the first interface, which is also the 
    private JButton[][] buttons;
    //the buttons in the square on the first interface
    private JPanel[] interfaces;
    //all the interfaces, used for inter-interface switch
    private int row;
    private int col;
    /*These two variables are both for the function of inputing row and column 
    numbers to select a square of grids.*/
    public static ArrayList<Pair<Student, Student>> deskMates = new ArrayList<>();
    //all the pairs of desk mates
    public static Map<String, Student> nameMap=new HashMap<>();
    /*to match the a Student variables and their names(in String class) 
    for conveniency in code)*/
    public static String destfile;
    //the file path that the generated seat chart will be stored at
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        InterFace1 = new javax.swing.JPanel();
        next1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        area00 = new javax.swing.JButton();
        area01 = new javax.swing.JButton();
        area02 = new javax.swing.JButton();
        area04 = new javax.swing.JButton();
        area03 = new javax.swing.JButton();
        area05 = new javax.swing.JButton();
        area06 = new javax.swing.JButton();
        area07 = new javax.swing.JButton();
        area10 = new javax.swing.JButton();
        area11 = new javax.swing.JButton();
        area12 = new javax.swing.JButton();
        area13 = new javax.swing.JButton();
        area14 = new javax.swing.JButton();
        area15 = new javax.swing.JButton();
        area16 = new javax.swing.JButton();
        area17 = new javax.swing.JButton();
        area20 = new javax.swing.JButton();
        area21 = new javax.swing.JButton();
        area22 = new javax.swing.JButton();
        area23 = new javax.swing.JButton();
        area24 = new javax.swing.JButton();
        area25 = new javax.swing.JButton();
        area26 = new javax.swing.JButton();
        area27 = new javax.swing.JButton();
        area30 = new javax.swing.JButton();
        area31 = new javax.swing.JButton();
        area32 = new javax.swing.JButton();
        area33 = new javax.swing.JButton();
        area34 = new javax.swing.JButton();
        area35 = new javax.swing.JButton();
        area36 = new javax.swing.JButton();
        area37 = new javax.swing.JButton();
        area40 = new javax.swing.JButton();
        area41 = new javax.swing.JButton();
        area42 = new javax.swing.JButton();
        area43 = new javax.swing.JButton();
        area44 = new javax.swing.JButton();
        area45 = new javax.swing.JButton();
        area46 = new javax.swing.JButton();
        area47 = new javax.swing.JButton();
        area50 = new javax.swing.JButton();
        area51 = new javax.swing.JButton();
        area52 = new javax.swing.JButton();
        area53 = new javax.swing.JButton();
        area54 = new javax.swing.JButton();
        area55 = new javax.swing.JButton();
        area56 = new javax.swing.JButton();
        area57 = new javax.swing.JButton();
        legend_red = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        legend_blue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rowField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        colField = new javax.swing.JTextField();
        Assure1 = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        InterFace2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filePathField = new javax.swing.JTextField();
        pathSampleLabel = new javax.swing.JLabel();
        next2 = new javax.swing.JButton();
        Assure2 = new javax.swing.JButton();
        Previous1 = new javax.swing.JButton();
        InterFace3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        requirementLabel2 = new javax.swing.JLabel();
        FBTextField1 = new javax.swing.JTextField();
        AddFB1 = new javax.swing.JButton();
        CancelFB1 = new javax.swing.JButton();
        FBTextField2 = new javax.swing.JTextField();
        AddFB2 = new javax.swing.JButton();
        CancelFB2 = new javax.swing.JButton();
        FBTextField3 = new javax.swing.JTextField();
        AddFB3 = new javax.swing.JButton();
        CancelFB3 = new javax.swing.JButton();
        FBTextField4 = new javax.swing.JTextField();
        AddFB4 = new javax.swing.JButton();
        CancelFB4 = new javax.swing.JButton();
        FBTextField5 = new javax.swing.JTextField();
        AddFB5 = new javax.swing.JButton();
        CancelFB5 = new javax.swing.JButton();
        FBTextField6 = new javax.swing.JTextField();
        AddFB6 = new javax.swing.JButton();
        CancelFB6 = new javax.swing.JButton();
        Previous2 = new javax.swing.JButton();
        next3 = new javax.swing.JButton();
        InterFace4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DMTextFieldB1 = new javax.swing.JTextField();
        AddDM1 = new javax.swing.JButton();
        CancelDM1 = new javax.swing.JButton();
        DMTextFieldA1 = new javax.swing.JTextField();
        DMTextFieldA2 = new javax.swing.JTextField();
        DMTextFieldB2 = new javax.swing.JTextField();
        AddDM2 = new javax.swing.JButton();
        CancelDM2 = new javax.swing.JButton();
        DMTextFieldA3 = new javax.swing.JTextField();
        DMTextFieldB3 = new javax.swing.JTextField();
        AddDM3 = new javax.swing.JButton();
        CancelDM3 = new javax.swing.JButton();
        Previous3 = new javax.swing.JButton();
        next4 = new javax.swing.JButton();
        InterFace5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        filePathField2 = new javax.swing.JTextField();
        pathSampleLabel1 = new javax.swing.JLabel();
        next5 = new javax.swing.JButton();
        Assure3 = new javax.swing.JButton();
        Previous4 = new javax.swing.JButton();
        InterFace6 = new javax.swing.JPanel();
        generateButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        Previous5 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 200));

        next1.setText("next");
        next1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next1MouseClicked(evt);
            }
        });

        area27.setToolTipText("");

        area34.setToolTipText("");

        legend_red.setBackground(new java.awt.Color(255, 0, 0));

        jLabel5.setText("unselected");

        jLabel6.setText("selected");

        legend_blue.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(area30, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(area31, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(area32, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(area33, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(area34, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(area35, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(area36, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(area37, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(legend_blue, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(area20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area24, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area25, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area26, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area27, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(area40, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area41, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area42, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area43, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area44, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area45, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area46, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area47, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(area50, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area51, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area52, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area53, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area54, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area55, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area56, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area57, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(area10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(area00, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area01, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area02, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area03, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area04, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area05, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area06, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(area07, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(legend_red, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(area02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area07, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(area00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(area12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area17, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(area10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(area11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(legend_red, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area37, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(area36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(area30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(legend_blue, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area40, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(area41, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(area42, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(area43, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(area44, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(area45, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(area46, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(area47, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(area50, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area51, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area52, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area53, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area54, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area55, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area56, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area57, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        area00.getAccessibleContext().setAccessibleName("area00");
        area00.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setText("row:");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("please select the area of your seats");

        jLabel4.setText("col:");

        Assure1.setText("Assure");
        Assure1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assure1ActionPerformed(evt);
            }
        });

        clearButton.setText("clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InterFace1Layout = new javax.swing.GroupLayout(InterFace1);
        InterFace1.setLayout(InterFace1Layout);
        InterFace1Layout.setHorizontalGroup(
            InterFace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InterFace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterFace1Layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(next1))
                    .addGroup(InterFace1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Assure1))
                    .addGroup(InterFace1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InterFace1Layout.setVerticalGroup(
            InterFace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InterFace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rowField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(colField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Assure1))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InterFace1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next1)
                    .addComponent(clearButton))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.getAccessibleContext().setAccessibleName("");

        jLabel3.setText("Please enter the .csv file of your class information: ");

        pathSampleLabel.setText("e.g.C:\\Desktop\\Classmates.csv");

        next2.setText("next");
        next2.setEnabled(false);
        next2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next2MouseClicked(evt);
            }
        });

        Assure2.setText("Assure");
        Assure2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Assure2MouseClicked(evt);
            }
        });

        Previous1.setText("Previous");
        Previous1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Previous1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InterFace2Layout = new javax.swing.GroupLayout(InterFace2);
        InterFace2.setLayout(InterFace2Layout);
        InterFace2Layout.setHorizontalGroup(
            InterFace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(InterFace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InterFace2Layout.createSequentialGroup()
                        .addComponent(Previous1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Assure2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(next2))
                    .addGroup(InterFace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pathSampleLabel)
                        .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        InterFace2Layout.setVerticalGroup(
            InterFace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pathSampleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(InterFace2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next2)
                    .addComponent(Assure2)
                    .addComponent(Previous1))
                .addGap(45, 45, 45))
        );

        jLabel7.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel7.setText("please add requirements in this page.");

        jLabel9.setText("1. please add the names of the students who must sit in the front.");

        requirementLabel2.setText("2. please add the names of the students who must sit in the back.");

        AddFB1.setText("add");

        CancelFB1.setText("cancel");

        AddFB2.setText("add");

        CancelFB2.setText("cancel");

        AddFB3.setText("add");

        CancelFB3.setText("cancel");

        AddFB4.setText("add");

        CancelFB4.setText("cancel");

        AddFB5.setText("add");

        CancelFB5.setText("cancel");

        AddFB6.setText("add");

        CancelFB6.setText("cancel");

        Previous2.setText("Previous");
        Previous2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Previous2MouseClicked(evt);
            }
        });

        next3.setText("next");
        next3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InterFace3Layout = new javax.swing.GroupLayout(InterFace3);
        InterFace3.setLayout(InterFace3Layout);
        InterFace3Layout.setHorizontalGroup(
            InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace3Layout.createSequentialGroup()
                .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterFace3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InterFace3Layout.createSequentialGroup()
                                .addComponent(FBTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddFB6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelFB6))
                            .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(InterFace3Layout.createSequentialGroup()
                                    .addComponent(FBTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AddFB5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CancelFB5))
                                .addGroup(InterFace3Layout.createSequentialGroup()
                                    .addComponent(FBTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AddFB4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CancelFB4)))))
                    .addGroup(InterFace3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Previous2)
                            .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(requirementLabel2)
                                .addComponent(jLabel9)
                                .addGroup(InterFace3Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InterFace3Layout.createSequentialGroup()
                                            .addComponent(FBTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(AddFB3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CancelFB3))
                                        .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(InterFace3Layout.createSequentialGroup()
                                                .addComponent(FBTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AddFB2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CancelFB2))
                                            .addGroup(InterFace3Layout.createSequentialGroup()
                                                .addComponent(FBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AddFB1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CancelFB1)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(next3)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        InterFace3Layout.setVerticalGroup(
            InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FBTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFB1)
                    .addComponent(CancelFB1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FBTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFB2)
                    .addComponent(CancelFB2))
                .addGap(4, 4, 4)
                .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FBTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFB3)
                    .addComponent(CancelFB3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(requirementLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FBTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFB4)
                    .addComponent(CancelFB4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FBTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFB5)
                    .addComponent(CancelFB5))
                .addGap(4, 4, 4)
                .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FBTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFB6)
                    .addComponent(CancelFB6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InterFace3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Previous2)
                    .addComponent(next3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel8.setText("please add requirements in this page.");

        jLabel10.setText("3. please add the names of students who must be deskmates.");

        AddDM1.setText("add");

        CancelDM1.setText("cancel");

        AddDM2.setText("add");

        CancelDM2.setText("cancel");

        AddDM3.setText("add");

        CancelDM3.setText("cancel");

        Previous3.setText("Previous");
        Previous3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Previous3MouseClicked(evt);
            }
        });

        next4.setText("next");
        next4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InterFace4Layout = new javax.swing.GroupLayout(InterFace4);
        InterFace4.setLayout(InterFace4Layout);
        InterFace4Layout.setHorizontalGroup(
            InterFace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace4Layout.createSequentialGroup()
                .addGroup(InterFace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterFace4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(InterFace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)))
                    .addGroup(InterFace4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(InterFace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InterFace4Layout.createSequentialGroup()
                                .addComponent(DMTextFieldA2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DMTextFieldB2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddDM2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelDM2))
                            .addGroup(InterFace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InterFace4Layout.createSequentialGroup()
                                    .addComponent(DMTextFieldA3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DMTextFieldB3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AddDM3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CancelDM3))
                                .addGroup(InterFace4Layout.createSequentialGroup()
                                    .addComponent(DMTextFieldA1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DMTextFieldB1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AddDM1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CancelDM1))))))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InterFace4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Previous3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(next4)
                .addGap(37, 37, 37))
        );
        InterFace4Layout.setVerticalGroup(
            InterFace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(InterFace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DMTextFieldB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDM1)
                    .addComponent(CancelDM1)
                    .addComponent(DMTextFieldA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InterFace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DMTextFieldB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDM2)
                    .addComponent(CancelDM2)
                    .addComponent(DMTextFieldA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InterFace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DMTextFieldB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDM3)
                    .addComponent(CancelDM3)
                    .addComponent(DMTextFieldA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(InterFace4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Previous3)
                    .addComponent(next4))
                .addGap(19, 19, 19))
        );

        jLabel11.setText("Please enter the .csv file that will store the seat chart:");

        pathSampleLabel1.setText("e.g.C:\\users\\xxx\\Desktop\\SeatChart.csv");

        next5.setText("next");
        next5.setEnabled(false);
        next5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next5MouseClicked(evt);
            }
        });

        Assure3.setText("Assure");
        Assure3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Assure3MouseClicked(evt);
            }
        });

        Previous4.setText("Previous");
        Previous4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Previous4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InterFace5Layout = new javax.swing.GroupLayout(InterFace5);
        InterFace5.setLayout(InterFace5Layout);
        InterFace5Layout.setHorizontalGroup(
            InterFace5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace5Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addGroup(InterFace5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InterFace5Layout.createSequentialGroup()
                        .addComponent(Previous4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Assure3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(next5))
                    .addGroup(InterFace5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pathSampleLabel1)
                        .addComponent(filePathField2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        InterFace5Layout.setVerticalGroup(
            InterFace5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace5Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(filePathField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pathSampleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(InterFace5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next5)
                    .addComponent(Assure3)
                    .addComponent(Previous4))
                .addGap(72, 72, 72))
        );

        generateButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        generateButton.setText("GENERATE SEAT CHART NOW!");
        generateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateButtonMouseClicked(evt);
            }
        });

        redoButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        redoButton.setText("REDO SETTINGS");
        redoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redoButtonMouseClicked(evt);
            }
        });

        Previous5.setText("Previous");
        Previous5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Previous5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InterFace6Layout = new javax.swing.GroupLayout(InterFace6);
        InterFace6.setLayout(InterFace6Layout);
        InterFace6Layout.setHorizontalGroup(
            InterFace6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InterFace6Layout.createSequentialGroup()
                .addGroup(InterFace6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InterFace6Layout.createSequentialGroup()
                        .addGroup(InterFace6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InterFace6Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(generateButton))
                            .addGroup(InterFace6Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(redoButton)))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InterFace6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Previous5)))
                .addContainerGap())
        );
        InterFace6Layout.setVerticalGroup(
            InterFace6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InterFace6Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(generateButton)
                .addGap(18, 18, 18)
                .addComponent(redoButton)
                .addGap(32, 32, 32)
                .addComponent(Previous5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 175, Short.MAX_VALUE)
                .addComponent(InterFace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 176, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InterFace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InterFace3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InterFace4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(InterFace5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(318, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InterFace6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(InterFace1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InterFace2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InterFace3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InterFace4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(InterFace5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(85, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InterFace6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initComponents2() {
        interfaces = new JPanel[]{InterFace1, InterFace2, InterFace3,InterFace4,
            InterFace5,InterFace6};
        initInterface(InterFace1);
        buttons = new javax.swing.JButton[][]{
            {area00, area01, area02, area03, area04, area05, area06, area07},
            {area10, area11, area12, area13, area14, area15, area16, area17},
            {area20, area21, area22, area23, area24, area25, area26, area27},
            {area30, area31, area32, area33, area34, area35, area36, area37},
            {area40, area41, area42, area43, area44, area45, area46, area47},
            {area50, area51, area52, area53, area54, area55, area56, area57}};
        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < 8; j++) {
                buttons[i][j].setBackground(Color.red);
                addAreaOnClick(buttons[i][j], i, j);
                selectedButton[i][j] = false;
            }
        }
        addFBDMOnclick();
    }
    private void initInterface(JPanel inf) {
        for (JPanel i : interfaces) {
            i.setVisible(false);
            i.enableInputMethods(false);
        }
        inf.setVisible(true);
        inf.setVisible(true);   
    }
    
    private void Assure2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Assure2MouseClicked
        String path = filePathField.getText().trim();
        if (path.equals("") || path == null) {
            JOptionPane.showMessageDialog(jPanel2, "please enter the path");
            return;
        }
        File file = new File(path);
        readin(file);
        
        next2.setEnabled(true);
    }//GEN-LAST:event_Assure2MouseClicked
    private void Assure1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assure1ActionPerformed
        String txt = rowField.getText().trim();
        String txt2 = colField.getText().trim();
        try {
            col = Integer.parseInt(txt2);
            row = Integer.parseInt(txt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(jPanel2, "please enter an integer");
        }
        updateRowCol();
    }//GEN-LAST:event_Assure1ActionPerformed
    private void next1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next1MouseClicked
        initInterface(InterFace2);
    }//GEN-LAST:event_next1MouseClicked
    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        count = 0;
        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < 8; j++) {
                buttons[i][j].setBackground(Color.red);
                selectedButton[i][j] = false;
            }
        }
    }//GEN-LAST:event_clearButtonMouseClicked
    private void Previous1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous1MouseClicked
        initInterface(InterFace1);
    }//GEN-LAST:event_Previous1MouseClicked
    private void next2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next2MouseClicked
        initInterface(InterFace3);
    }//GEN-LAST:event_next2MouseClicked
    private void Previous2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous2MouseClicked
        initInterface(InterFace2);
    }//GEN-LAST:event_Previous2MouseClicked
    private void next3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next3MouseClicked
        initInterface(InterFace4);
    }//GEN-LAST:event_next3MouseClicked
    private void Previous3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous3MouseClicked
        initInterface(InterFace3);
    }//GEN-LAST:event_Previous3MouseClicked
    private void next4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next4MouseClicked
        initInterface(InterFace5);
    }//GEN-LAST:event_next4MouseClicked
    private void next5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next5MouseClicked
        initInterface(InterFace6);
    }//GEN-LAST:event_next5MouseClicked
    private void Assure3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Assure3MouseClicked
        String path = filePathField2.getText().trim();
        if (path.equals("") || path == null) {
            JOptionPane.showMessageDialog(jPanel2, "please enter the path");
            return;
        }
        destfile=path;
        next5.setEnabled(true);
    }//GEN-LAST:event_Assure3MouseClicked
    private void Previous4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous4MouseClicked
        initInterface(InterFace4);
    }//GEN-LAST:event_Previous4MouseClicked
    private void Previous5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Previous5MouseClicked
        initInterface(InterFace5);
    }//GEN-LAST:event_Previous5MouseClicked
    private void generateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateButtonMouseClicked
        try{
            SeatChart.getSeatChart();        
            JOptionPane.showMessageDialog(jPanel2, "the seat chart is generated successfully");
        }
        catch(StackOverflowError e){
            JOptionPane.showMessageDialog(jPanel2, "sorry, there is no possible seat arrangement for your requirement.");
        }
    }//GEN-LAST:event_generateButtonMouseClicked
    private void redoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redoButtonMouseClicked
        initInterface(InterFace1);
    }//GEN-LAST:event_redoButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
   
    private void addAreaOnClick(JButton b, int x, int y) {
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StateReverse(x, y);
            }
        });
    }
    private void FBClickListener(JButton add, JButton cancel, boolean isAdd,
            boolean isFront, JTextField tf) {
        JButton b = isAdd ? add : cancel, c = isAdd ? cancel : add;
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String name = tf.getText().trim();
                if (isAdd) {
                    if (name.equals("") || name == null) {
                        JOptionPane.showMessageDialog(jPanel2, "please enter a name");
                        return;
                    }
                    Student s = nameMap.get(name);
                    if (s == null) {
                        JOptionPane.showMessageDialog(jPanel2, "please enter the correct name");
                        return;
                    }
                    tf.setEnabled(false);
                }else{
                    tf.setEnabled(true);
                    tf.setText("");
                }
                b.setEnabled(false);
                c.setEnabled(true);
                Student s = nameMap.get(name);
                if (isFront) {
                    s.setMustFront(isAdd);
                } else {
                    s.setMustBack(isAdd);
                }
            }
        });
    }
    private void DMClickListener(JButton add, JButton cancel, boolean isAdd,
            JTextField tf1, JTextField tf2){
        JButton b = isAdd ? add : cancel, c = isAdd ? cancel : add;
        b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String name1 = tf1.getText().trim();
                String name2 = tf2.getText().trim();
                if (isAdd) {
                    if (name1.equals("") || name1 == null || name2 == null ||
                            name2.equals("")) {
                        JOptionPane.showMessageDialog(jPanel2, "please enter a name");
                        return;
                    }
                    Student s1 = nameMap.get(name1);
                    Student s2 = nameMap.get(name2);
                    if (s1 == null || s2==null) {
                        JOptionPane.showMessageDialog(jPanel2, "please enter the correct name");
                        return;
                    }
                    if (s1.equals(s2)){
                        JOptionPane.showMessageDialog(jPanel2, "please enter different names");
                        return;
                    }
                    tf1.setEnabled(false);tf2.setEnabled(false);
                }else{
                    tf1.setEnabled(true);tf2.setEnabled(true);
                    tf1.setText("");tf2.setText("");
                }
                b.setEnabled(false);
                c.setEnabled(true);
                Student s1 = nameMap.get(name1);
                Student s2 = nameMap.get(name2);
                deskMates.add(new Pair(s1, s2));
            }
        });
    }
    private void addFBDMOnclick() {
        FBClickListener(AddFB1, CancelFB1, true, true, FBTextField1);
        FBClickListener(AddFB1, CancelFB1, false, true, FBTextField1);
        FBClickListener(AddFB2, CancelFB2, true, true, FBTextField2);
        FBClickListener(AddFB2, CancelFB2, false, true, FBTextField2);
        FBClickListener(AddFB3, CancelFB3, true, true, FBTextField3);
        FBClickListener(AddFB3, CancelFB3, false, true, FBTextField3);
        FBClickListener(AddFB4, CancelFB4, true, false, FBTextField4);
        FBClickListener(AddFB4, CancelFB4, false, false, FBTextField4);
        FBClickListener(AddFB5, CancelFB5, true, false, FBTextField5);
        FBClickListener(AddFB5, CancelFB5, false, false, FBTextField5);
        FBClickListener(AddFB6, CancelFB6, true, false, FBTextField6);        
        FBClickListener(AddFB6, CancelFB6, false, false, FBTextField6);
        CancelFB1.setEnabled(false);CancelFB2.setEnabled(false);
        CancelFB3.setEnabled(false);CancelFB4.setEnabled(false);      
        CancelFB5.setEnabled(false);CancelFB6.setEnabled(false);
        DMClickListener(AddDM1, CancelDM1, true, DMTextFieldA1, DMTextFieldB1);
        DMClickListener(AddDM2, CancelDM2, true, DMTextFieldA2, DMTextFieldB2);
        DMClickListener(AddDM3, CancelDM3, true, DMTextFieldA3, DMTextFieldB3);
        DMClickListener(AddDM1, CancelDM1, false, DMTextFieldA1, DMTextFieldB1);
        DMClickListener(AddDM2, CancelDM2, false, DMTextFieldA2, DMTextFieldB2);
        DMClickListener(AddDM3, CancelDM3, false, DMTextFieldA3, DMTextFieldB3);
        CancelDM1.setEnabled(false);
        CancelDM2.setEnabled(false);
        CancelDM3.setEnabled(false);
    }  
    private void readin(File file) {
        ArrayList<String> names = new ArrayList<>();
        try {
            Scanner scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                String line=scanner.nextLine().trim();
                String[] name=line.split(",");
                names.addAll(Arrays.asList(name));
            }
            if (names.size() != count) {
                JOptionPane.showMessageDialog(jPanel2, "the number of students is "
                        + "not equal to the number of seats selected");
                return;
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(jPanel2, "the file path is not correct");
            return;
        }
        for (String str : names) {
            nameMap.put(str, new Student(str));
        }
    } 
    private void StateReverse(int i, int j) {
        selectedButton[i][j] = !selectedButton[i][j];
        if (selectedButton[i][j]) {
            buttons[i][j].setBackground(Color.BLUE);
            count++;
        } else {
            buttons[i][j].setBackground(Color.RED);
            count--;
        }
    }
    private void updateRowCol() {
        if (row > 6 || col > 8) {
            JOptionPane.showMessageDialog(jPanel2, "sorry, the number you enter is too large");
            return;
        }
        if (row != 0 && col != 0) {
            for (int i = 0; i < row; i++) {
                for (int j = 0; j < col; j++) {
                    if (!selectedButton[i][j]) {
                        count++;
                    }
                    selectedButton[i][j] = true;
                    buttons[i][j].setBackground(Color.BLUE);
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDM1;
    private javax.swing.JButton AddDM2;
    private javax.swing.JButton AddDM3;
    private javax.swing.JButton AddFB1;
    private javax.swing.JButton AddFB2;
    private javax.swing.JButton AddFB3;
    private javax.swing.JButton AddFB4;
    private javax.swing.JButton AddFB5;
    private javax.swing.JButton AddFB6;
    private javax.swing.JButton Assure1;
    private javax.swing.JButton Assure2;
    private javax.swing.JButton Assure3;
    private javax.swing.JButton CancelDM1;
    private javax.swing.JButton CancelDM2;
    private javax.swing.JButton CancelDM3;
    private javax.swing.JButton CancelFB1;
    private javax.swing.JButton CancelFB2;
    private javax.swing.JButton CancelFB3;
    private javax.swing.JButton CancelFB4;
    private javax.swing.JButton CancelFB5;
    private javax.swing.JButton CancelFB6;
    private javax.swing.JTextField DMTextFieldA1;
    private javax.swing.JTextField DMTextFieldA2;
    private javax.swing.JTextField DMTextFieldA3;
    private javax.swing.JTextField DMTextFieldB1;
    private javax.swing.JTextField DMTextFieldB2;
    private javax.swing.JTextField DMTextFieldB3;
    private javax.swing.JTextField FBTextField1;
    private javax.swing.JTextField FBTextField2;
    private javax.swing.JTextField FBTextField3;
    private javax.swing.JTextField FBTextField4;
    private javax.swing.JTextField FBTextField5;
    private javax.swing.JTextField FBTextField6;
    private javax.swing.JPanel InterFace1;
    private javax.swing.JPanel InterFace2;
    private javax.swing.JPanel InterFace3;
    private javax.swing.JPanel InterFace4;
    private javax.swing.JPanel InterFace5;
    private javax.swing.JPanel InterFace6;
    private javax.swing.JButton Previous1;
    private javax.swing.JButton Previous2;
    private javax.swing.JButton Previous3;
    private javax.swing.JButton Previous4;
    private javax.swing.JButton Previous5;
    private javax.swing.JButton area00;
    private javax.swing.JButton area01;
    private javax.swing.JButton area02;
    private javax.swing.JButton area03;
    private javax.swing.JButton area04;
    private javax.swing.JButton area05;
    private javax.swing.JButton area06;
    private javax.swing.JButton area07;
    private javax.swing.JButton area10;
    private javax.swing.JButton area11;
    private javax.swing.JButton area12;
    private javax.swing.JButton area13;
    private javax.swing.JButton area14;
    private javax.swing.JButton area15;
    private javax.swing.JButton area16;
    private javax.swing.JButton area17;
    private javax.swing.JButton area20;
    private javax.swing.JButton area21;
    private javax.swing.JButton area22;
    private javax.swing.JButton area23;
    private javax.swing.JButton area24;
    private javax.swing.JButton area25;
    private javax.swing.JButton area26;
    private javax.swing.JButton area27;
    private javax.swing.JButton area30;
    private javax.swing.JButton area31;
    private javax.swing.JButton area32;
    private javax.swing.JButton area33;
    private javax.swing.JButton area34;
    private javax.swing.JButton area35;
    private javax.swing.JButton area36;
    private javax.swing.JButton area37;
    private javax.swing.JButton area40;
    private javax.swing.JButton area41;
    private javax.swing.JButton area42;
    private javax.swing.JButton area43;
    private javax.swing.JButton area44;
    private javax.swing.JButton area45;
    private javax.swing.JButton area46;
    private javax.swing.JButton area47;
    private javax.swing.JButton area50;
    private javax.swing.JButton area51;
    private javax.swing.JButton area52;
    private javax.swing.JButton area53;
    private javax.swing.JButton area54;
    private javax.swing.JButton area55;
    private javax.swing.JButton area56;
    private javax.swing.JButton area57;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField colField;
    private javax.swing.JTextField filePathField;
    private javax.swing.JTextField filePathField2;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton legend_blue;
    private javax.swing.JButton legend_red;
    private javax.swing.JButton next1;
    private javax.swing.JButton next2;
    private javax.swing.JButton next3;
    private javax.swing.JButton next4;
    private javax.swing.JButton next5;
    private javax.swing.JLabel pathSampleLabel;
    private javax.swing.JLabel pathSampleLabel1;
    private javax.swing.JButton redoButton;
    private javax.swing.JLabel requirementLabel2;
    private javax.swing.JTextField rowField;
    // End of variables declaration//GEN-END:variables
}
